// ---------------------------------------------------------------------------
// Trinetra AI – Core type definitions for the telemetry/incident engine
// ---------------------------------------------------------------------------

/** A single request log entry produced by the telemetry simulator */
export interface TelemetryLog {
  id: string
  timestamp: Date
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH"
  path: string
  statusCode: number
  latencyMs: number
  service: string
  error?: string
}

/** Severity levels for incidents */
export type Severity = "low" | "medium" | "high" | "critical"

/** Lifecycle status of an incident */
export type IncidentStatus = "investigating" | "identified" | "monitoring" | "resolved"

/** An incident generated by the anomaly detection engine */
export interface Incident {
  id: string
  title: string
  description: string
  severity: Severity
  status: IncidentStatus
  affectedRoute: string
  service: string
  rootCause: string
  confidence: number
  recommendedFix: string
  createdAt: Date
  updatedAt: Date
  resolvedAt?: Date
}

/** A single data point used by time-series charts */
export interface ChartDataPoint {
  time: string
  latency: number
  p99: number
  requests: number
  errors: number
}

/** Aggregated metrics shown in the hero cards */
export interface SystemMetrics {
  systemHealth: number      // 0-100 percentage
  requestsPerMin: number
  avgLatencyMs: number
  errorRate: number         // 0-100 percentage
  prevSystemHealth: number
  prevRequestsPerMin: number
  prevAvgLatencyMs: number
  prevErrorRate: number
}

/** Active failure scenario injected via simulation controls */
export type FailureScenario = "database" | "openai" | "traffic" | "auth"

/** Guided demo scenario keys */
export type DemoScenarioKey = "openai_meltdown" | "database_exhaustion" | "traffic_surge" | "auth_storm"

/** A single remediation action proposed by AI */
export interface RemediationAction {
  id: string
  incidentId: string
  actionKey: string
  title: string
  description: string
  status: "recommended" | "executing" | "completed"
  progress: number
  command: string
  logs: string[]
}

/** A single event in the cinematic timeline */
export interface TimelineEvent {
  id: string
  timestamp: Date
  title: string
  description: string
  severity: "info" | "warning" | "error" | "success"
  incidentId?: string
}

/** A message in the Ask Trinetra chat panel */
export interface ChatMessage {
  id: string
  role: "user" | "assistant" | "system"
  content: string
  timestamp: Date
  isStreaming?: boolean
}

/** The full state surface of the telemetry system */
export interface TelemetryState {
  logs: TelemetryLog[]
  incidents: Incident[]
  metrics: SystemMetrics
  chartData: ChartDataPoint[]
  activeFailures: Set<FailureScenario>
  isRunning: boolean
  activeScenario: DemoScenarioKey | null
  remediationActions: RemediationAction[]
  aiConfidenceScore: number
}
